# this docker file ist deployed on the remote server

version: '3.3'
services:
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./db-postgres/db:/var/lib/postgresql/data
      - ./db-postgres/import:/import
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  appsrv:
    image: ghcr.io/mandelrosaliejanina/mealcounter-reload-appsrv:latest
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - db
  nginx:
    image: ghcr.io/mandelrosaliejanina/mealcounter-reload-nginx:latest
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 80:80
    depends_on:
      - appsrv
volumes:
  database:
